# train_config.yaml
model: yolo_weights/yolov9s.pt
data: data.yaml
epochs: 100
imgsz: 256
batch: 8
# workers: 0
project: runs/vehicle_detection
name: yolov9_vehicle_detect
# Data augment
degrees: 10.0
translate: 0.1
scale: 0.5
shear: 2.0
perspective: 0.0
# Màu sắc
hsv_h: 0.1
hsv_s: 0.6
hsv_v: 0.3
# Biến đổi ảnh
degrees: 30
shear: 10
fliplr: 0.5
flipud: 0
mosaic: 1.0